# Generated by Django 2.1.7 on 2019-04-05 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_back', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='id',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='rest_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cust_id',
        ),
        migrations.AddField(
            model_name='manager',
            name='man_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default=None, upload_to='restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='man_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Manager'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='media/item'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='feedback',
            name='cust_id',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='orders.Customer'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rest_id',
            field=models.ForeignKey(default=1007, on_delete=django.db.models.deletion.CASCADE, to='orders.Restaurant'),
        ),
        migrations.AddField(
            model_name='bill',
            name='cust_id',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='orders.Customer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='rest_id',
            field=models.ForeignKey(default=1007, on_delete=django.db.models.deletion.CASCADE, to='orders.Restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orders.Bill'),
        ),
    ]
