# Generated by Django 2.1.7 on 2019-04-06 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190406_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('ad_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
